import {createClient} from '@supabase/supabase-js';
import {records,put,setting} from './store';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
export const cloud=url&&key?createClient(url,key):null;
export let membership=null;
let syncing=false;
export async function connect(){if(!cloud)return null;const {data:{user}}=await cloud.auth.getUser();if(!user){membership=null;return null;}const {data,error}=await cloud.from('memberships').select('*').eq('user_id',user.id).single();if(error)throw Error('Your administrator needs to add your team membership.');membership=data;return data;}
export async function sync(){if(!cloud||!membership||!navigator.onLine||syncing)return;syncing=true;try{const local=await records();for(const record of local.filter(r=>r.dirty&&r.ownerId===membership.user_id)) {const {data,error}=await cloud.rpc('save_record',{record_id:record.id,record_kind:record.kind,record_payload:record,expected_revision:record.revision||0});if(error){if(error.message.includes('conflict')){await put({...record,conflict:true});continue;}throw error;}await put({...record,revision:data,dirty:false,conflict:false,syncedAt:new Date().toISOString()});}const {data,error}=await cloud.from('records').select('*');if(error)throw error;for(const row of data){const current=await records();const ours=current.find(r=>r.id===row.id);if(ours?.dirty)continue;await put({...row.payload,id:row.id,kind:row.kind,ownerId:row.owner_id,revision:row.revision,dirty:false,syncedAt:row.updated_at});}await setting('lastSync',new Date().toISOString());}finally{syncing=false;}}
export async function translateRecord(record){if(!cloud||!membership||!navigator.onLine)return record;const {data,error}=await cloud.functions.invoke('translate-note',{body:{note:record.note,advice:record.advice,source:record.language}});if(error||!data?.translations)return record;return {...record,translations:data.translations};}
